package com.qfc.yft.ui.custom.list;

public interface ListItemImpl {
	public enum Type{
		ALBUM,LOCAL,APIC,CHOOSE,PM,
		IP_LOCALHISTORY,IP_COMPANY_SEARCH,IP_PRODUCT_SEARCH,IP_PEOPLE_SEARCH,IP_IMAGINE,
		IP_PRODUCT_MY,IP_COMPANY_MY,IP_PEOPLE_MY, IP_COMPANY_RECOMMEND,
		ORDER_SELL,ORDER_BUY;
	}


}
